services:
  app:
    build: .
    container_name: url-shortener
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - MONGODB_URI=mongodb://admin:y7jHf&DNWG15@mongodb:27017
      - SERVER_PORT=:8080
      - ALLOWED_CHARS=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
      - SHORT_CODE_LENGTH=6
    networks:
      - mongo-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=y7jHf&DNWG15
    networks:
      - mongo-network

volumes:
  mongodb_data:

networks:
  mongo-network:
    driver: bridge